const TN_ASSEMBLY_CONSTITUENCIES = [
  'Gummidipoondi',
  'Ponneri (SC)',
  'Tiruttani',
  'Thiruvallur',
  'Poonamallee (SC)',
  'Avadi',
  'Maduravoyal',
  'Ambattur',
  'Madavaram',
  'Thiruvottiyur',
  'Dr. Radhakrishnan Nagar',
  'Perambur',
  'Kolathur',
  'Villivakkam',
  'Thiru-Vi-Ka Nagar (SC)',
  'Egmore (SC)',
  'Royapuram',
  'Harbour',
  'Chepauk-Thiruvallikeni',
  'Thousand Lights',
  'Anna Nagar',
  'Virugampakkam',
  'Saidapet',
  'T. Nagar',
  'Mylapore',
  'Velachery',
  'Sholinganallur',
  'Alandur',
  'Sriperumbudur (SC)',
  'Pallavaram',
  'Tambaram',
  'Chengalpattu',
  'Thiruporur',
  'Cheyyur (SC)',
  'Madurantakam (SC)',
  'Uthiramerur',
  'Kancheepuram',
  'Arakkonam (SC)',
  'Sholingur',
  'Katpadi',
  'Ranipet',
  'Arcot',
  'Vellore',
  'Anaikattu',
  'Kilvaithinankuppam (SC)',
  'Gudiyattam (SC)',
  'Vaniyambadi',
  'Ambur',
  'Jolarpet',
  'Tirupattur',
  'Uthangarai (SC)',
  'Bargur',
  'Krishnagiri',
  'Veppanahalli',
  'Hosur',
  'Thalli',
  'Palacode',
  'Pennagaram',
  'Dharmapuri',
  'Pappireddippatti',
  'Harur (SC)',
  'Chengam (SC)',
  'Tiruvannamalai',
  'Kilpennathur',
  'Kalasapakkam',
  'Polur',
  'Arani',
  'Cheyyar',
  'Vandavasi (SC)',
  'Gingee',
  'Mailam',
  'Tindivanam (SC)',
  'Vanur (SC)',
  'Villupuram',
  'Vikravandi',
  'Tirukkoyilur',
  'Ulundurpettai',
  'Rishivandiyam',
  'Sankarapuram',
  'Kallakurichi (SC)',
  'Gangavalli (SC)',
  'Attur (SC)',
  'Yercaud (ST)',
  'Omalur',
  'Mettur',
  'Edappadi',
  'Sankari',
  'Salem West',
  'Salem North',
  'Salem South',
  'Veerapandi',
  'Rasipuram (SC)',
  'Senthamangalam (ST)',
  'Namakkal',
  'Paramathi Velur',
  'Tiruchengodu',
  'Kumarapalayam',
  'Erode East',
  'Erode West',
  'Modakkurichi',
  'Dharapuram (SC)',
  'Kangayam',
  'Perundurai',
  'Bhavani',
  'Anthiyur',
  'Gobichettipalayam',
  'Bhavanisagar (SC)',
  'Udhagamandalam',
  'Gudalur (SC)',
  'Coonoor',
  'Mettupalayam',
  'Avanashi (SC)',
  'Tiruppur North',
  'Tiruppur South',
  'Palladam',
  'Sulur',
  'Kavundampalayam',
  'Coimbatore North',
  'Thondamuthur',
  'Coimbatore South',
  'Singanallur',
  'Kinathukadavu',
  'Pollachi',
  'Valparai (SC)',
  'Udumalaipettai',
  'Madathukulam',
  'Palani',
  'Oddanchatram',
  'Athoor',
  'Nilakottai (SC)',
  'Natham',
  'Dindigul',
  'Vedasandur',
  'Aravakurichi',
  'Karur',
  'Krishnarayapuram (SC)',
  'Kulithalai',
  'Manapparai',
  'Srirangam',
  'Tiruchirappalli West',
  'Tiruchirappalli East',
  'Thiruverumbur',
  'Lalgudi',
  'Manachanallur',
  'Musiri',
  'Thuraiyur (SC)',
  'Perambalur (SC)',
  'Kunnam',
  'Ariyalur',
  'Jayankondam',
  'Tittakudi (SC)',
  'Vriddhachalam',
  'Neyveli',
  'Panruti',
  'Cuddalore',
  'Kurinjipadi',
  'Bhuvanagiri',
  'Chidambaram',
  'Kattumannarkoil (SC)',
  'Sirkazhi (SC)',
  'Mayiladuthurai',
  'Poompuhar',
  'Nagapattinam',
  'Kilvelur (SC)',
  'Vedaranyam',
  'Thiruthuraipoondi (SC)',
  'Mannargudi',
  'Thiruvarur',
  'Nannilam',
  'Thiruvidaimarudur (SC)',
  'Kumbakonam',
  'Papanasam',
  'Thiruvaiyaru',
  'Thanjavur',
  'Orathanadu',
  'Pattukkottai',
  'Peravurani',
  'Gandarvakottai (SC)',
  'Viralimalai',
  'Pudukkottai',
  'Thirumayam',
  'Alangudi',
  'Aranthangi',
  'Karaikudi',
  'Tiruppattur',
  'Sivaganga',
  'Manamadurai (SC)',
  'Melur',
  'Madurai East',
  'Sholavandan (SC)',
  'Madurai North',
  'Madurai South',
  'Madurai Central',
  'Madurai West',
  'Thiruparankundram',
  'Thirumangalam',
  'Usilampatti',
  'Andipatti',
  'Periyakulam (SC)',
  'Bodinayakanur',
  'Cumbum',
  'Rajapalayam',
  'Srivilliputhur (SC)',
  'Sattur',
  'Sivakasi',
  'Virudhunagar',
  'Aruppukkottai',
  'Tiruchuli',
  'Paramakudi (SC)',
  'Tiruvadanai',
  'Ramanathapuram',
  'Mudhukulathur',
  'Vilathikulam',
  'Thoothukudi',
  'Tiruchendur',
  'Srivaikuntam',
  'Ottapidaram (SC)',
  'Kovilpatti',
  'Sankarankovil (SC)',
  'Vasudevanallur (SC)',
  'Kadayanallur',
  'Tenkasi',
  'Alangulam',
  'Tirunelveli',
  'Ambasamudram',
  'Palayamkottai',
  'Nanguneri',
  'Radhapuram',
  'Kanniyakumari',
  'Nagercoil',
  'Colachel',
  'Padmanabhapuram',
  'Vilavancode',
  'Killiyoor',
].map((name, index) => ({ id: index + 1, name }));

const normalizeWardName = (value) => String(value || '').trim().toLowerCase();

const findWard = (value) => {
  const key = normalizeWardName(value);
  return TN_ASSEMBLY_CONSTITUENCIES.find((ward) => normalizeWardName(ward.name) === key);
};

module.exports = {
  TN_ASSEMBLY_CONSTITUENCIES,
  findWard,
};
